---
roles:
  - name: trombik.freebsd_pkg_repo
  - name: trombik.apt_repo
  - name: trombik.redhat_repo
  - name: trombik.sensu_go_agent
  - name: trombik.language_ruby
  - name: trombik.cfssl
collections:
  - name: sensu.sensu_go
