---

- name: Install required packages
  apt:
    name:
      - python3-bcrypt
    state: present

- name: Install sensu_go_backend_extra_packages
  apt:
    name: "{{ sensu_go_backend_extra_packages }}"
    state: present

- name: Install sensu_go_backend_package
  apt:
    name: "{{ sensu_go_backend_package }}"
    state: present

- name: Enable sensu_go_backend_service
  service:
    name: "{{ sensu_go_backend_service }}"
    enabled: yes

- name: Create /etc/default/sensu-backend
  template:
    src: Debian.default.j2
    dest: /etc/default/sensu-backend
    validate: sh -n %s
  notify:
    - Restart sensu_go_backend
