---

- name: Install sensu_go_backend_extra_python_packages
  yum:
    name: "{{ sensu_go_backend_extra_python_packages }}"
    state: present

- name: Install sensu_go_backend_extra_packages
  yum:
    name: "{{ sensu_go_backend_extra_packages }}"
    state: present

- name: Install sensu_go_backend_package
  yum:
    name: "{{ sensu_go_backend_package }}"
    state: present

- name: Enable sensu_go_backend_service
  service:
    name: "{{ sensu_go_backend_service }}"
    enabled: yes

- name: Create /etc/sysconfig/sensu-backend
  template:
    src: RedHat.sysconfig.j2
    dest: /etc/sysconfig/sensu-backend
    validate: sh -n %s
  notify:
    - Restart sensu_go_backend
