---
# tasks file for ansible-role-sensu_go_backend

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create sensu_go_backend_log_dir directory
  file:
    path: "{{ sensu_go_backend_log_dir }}"
    mode: 0755
    owner: "{{ sensu_go_backend_user }}"
    group: "{{ sensu_go_backend_group }}"
    state: directory
  notify: Restart sensu_go_backend

- name: Create sensu_go_backend_state_dir directory
  file:
    path: "{{ sensu_go_backend_state_dir }}"
    mode: 0755
    owner: "{{ sensu_go_backend_user }}"
    group: "{{ sensu_go_backend_group }}"
    state: directory
  notify: Restart sensu_go_backend

- name: Create sensu_go_backend_cache_dir directory
  file:
    path: "{{ sensu_go_backend_cache_dir }}"
    mode: 0755
    owner: "{{ sensu_go_backend_user }}"
    group: "{{ sensu_go_backend_group }}"
    state: directory
  notify: Restart sensu_go_backend

- name: Create sensu_go_backend_conf_file
  template:
    src: sensu-backend.yml.j2
    dest: "{{ sensu_go_backend_conf_file }}"
    # validate: echo %s
  notify: Restart sensu_go_backend

- name: Start sensu_go_backend
  service:
    name: "{{ sensu_go_backend_service }}"
    state: started

- name: Include flush_handlers.yml
  # XXX workaround `[WARNING]: flush_handlers task does not support when
  # conditional`
  # https://github.com/ansible/ansible/issues/41313
  include_tasks: flush_handlers.yml
  when:
    - sensu_go_backend_flush_handlers

- name: Configure sensu_go_backend_namespaces
  sensu.sensu_go.namespace:
    auth: "{{ item['namespace']['auth'] | default(omit) }}"
    name: "{{ item['namespace']['name'] }}"
    state: "{{ item['namespace']['state'] | default(omit) }}"
  with_items: "{{ sensu_go_backend_namespaces }}"

- name: Configure sensu_go_backend_roles
  sensu.sensu_go.role:
    auth: "{{ item['role']['auth'] | default(omit) }}"
    name: "{{ item['role']['name'] }}"
    namespace: "{{ item['role']['namespace'] | default(omit) }}"
    rules: "{{ item['role']['rules'] | default(omit) }}"
    state: "{{ item['role']['state'] | default(omit) }}"
  with_items: "{{ sensu_go_backend_roles }}"

- name: Configure sensu_go_backend_users
  sensu.sensu_go.user:
    auth: "{{ item['user']['auth'] | default(omit) }}"
    groups: "{{ item['user']['group'] | default(omit) }}"
    name: "{{ item['user']['name'] }}"
    password: "{{ item['user']['password'] | default(omit) }}"
    state: "{{ item['user']['state'] | default(omit) }}"
  with_items: "{{ sensu_go_backend_users }}"
  register: __sensu_go_backend_users_result
  changed_when: __sensu_go_backend_users_result['changed'] and not sensu_go_backend_users_ignore_changed

- name: Configure sensu_go_backend_assets
  sensu.sensu_go.asset:
    annotations: "{{ item['asset']['annotations'] | default(omit) }}"
    auth: "{{ item['asset']['auth'] | default(omit) }}"
    builds: "{{ item['asset']['builds'] | default(omit) }}"
    labels: "{{ item['asset']['labels'] | default(omit) }}"
    name: "{{ item['asset']['name'] }}"
    namespace: "{{ item['asset']['namespace'] | default(omit) }}"
    state: "{{ item['asset']['state'] | default(omit) }}"
  with_items: "{{ sensu_go_backend_assets }}"

- name: Configure sensu_go_backend_checks
  sensu.sensu_go.check:
    annotations: "{{ item['check']['annotations'] | default(omit) }}"
    auth: "{{ item['check']['auth'] | default(omit) }}"
    check_hooks: "{{ item['check']['check_hooks'] | default(omit) }}"
    command: "{{ item['check']['command'] | default(omit) }}"
    cron: "{{ item['check']['cron'] | default(omit) }}"
    env_vars: "{{ item['check']['env_vars'] | default(omit) }}"
    handlers: "{{ item['check']['handlers'] | default(omit) }}"
    high_flap_threshold: "{{ item['check']['high_flap_threshold'] | default(omit) }}"
    interval: "{{ item['check']['interval'] | default(omit) }}"
    labels: "{{ item['check']['labels'] | default(omit) }}"
    low_flap_threshold: "{{ item['check']['low_flap_threshold'] | default(omit) }}"
    name: "{{ item['check']['name'] }}"
    namespace: "{{ item['check']['namespace'] | default(omit) }}"
    output_metric_format: "{{ item['check']['output_metric_format'] | default(omit) }}"
    output_metric_handlers: "{{ item['check']['output_metric_handlers'] | default(omit) }}"
    publish: "{{ item['check']['publish'] | default(omit) }}"
    round_robin: "{{ item['check']['round_robin'] | default(omit) }}"
    runtime_assets: "{{ item['check']['runtime_assets'] | default(omit) }}"
    state: "{{ item['check']['state'] | default(omit) }}"
    stdin: "{{ item['check']['stdin'] | default(omit) }}"
    subscriptions: "{{ item['check']['subscriptions'] | default(omit) }}"
    timeout: "{{ item['check']['timeout'] | default(omit) }}"
    ttl: "{{ item['check']['ttl'] | default(omit) }}"
  with_items: "{{ sensu_go_backend_checks }}"
