---

- name: Restart sensu_go_backend
  service:
    name: "{{ sensu_go_backend_service }}"
    state: restarted
  notify:
    - Wait for sensu_go_backend

- name: Wait for sensu_go_backend
  wait_for:
    host: "{{ sensu_go_backend_api_host }}"
    port: "{{ sensu_go_backend_api_port }}"

- name: Configure initial admin account
  command:
    cmd: sensu-backend init
  environment:
    SENSU_BACKEND_CLUSTER_ADMIN_USERNAME: "{{ sensu_go_backend_admin_account }}"
    SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD: "{{ sensu_go_backend_admin_password }}"
